name: Python Tests

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip

    - name: Test with pytest
      run: |
        pip install pytest pytest-cov
        pytest test.py --doctest-modules --junitxml=junit/test-results.xml --cov=com --cov-report=xml --cov-report=html