name: Python Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install Python 3.13
      run: |
        sudo apt update
        sudo apt install -y wget build-essential libssl-dev libffi-dev zlib1g-dev
        wget https://www.python.org/ftp/python/3.13.0/Python-3.13.0.tgz
        tar -xf Python-3.13.0.tgz
        cd Python-3.13.0
        ./configure --enable-optimizations
        make -j$(nproc)
        sudo make altinstall
        python3.13 --version

    - name: Install dependencies
      run: |
        python3.13 -m pip install --upgrade pip
        python3.13 -m pip install -r requirements.txt

    - name: Test with pytest
      run: |
        python3.13 -m pip install pytest pytest-cov
        python3.13 -m pytest test.py --doctest-modules --junitxml=junit/test-results.xml --cov=com --cov-report=xml --cov-report=html